name: Build artifacts

on:
  push:
    tags: [ "*" ]

jobs:
    build:
        runs-on: windows-latest

        steps:
          - name: Create executable
            uses: sayyid5416/pyinstaller@v1
            with:
              python_ver: '3.10'
              spec: 'launcher.py'
              requirements: 'requirements.txt'
              options: --onefile, --name anime_rpc, --optimize 2, --additional-hooks-dir=.
              clean_checkout: false
          - name: Get version
            id: get_version
            shell: bash
            run: echo "version=$(python -c 'import anime_rpc; print(anime_rpc.__version__)')" >> $GITHUB_OUTPUT
          - name: Zip the module
            run: |
              mv LICENSE ./dist/
              Compress-Archive -Path dist/* -Destination anime_rpc_win.zip
          - name: Create release
            id: create_release
            uses: ncipollo/release-action@v1
            with:
                tag: v${{ steps.get_version.outputs.version }}
                name: Release v${{ steps.get_version.outputs.version }}
                artifacts: "./anime_rpc_win.zip"