name: Build artifacts

on:
  push:
    branches: [main]
    paths: [anime_rpc/__init__.py]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build executable
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: |
          pip install -r requirements.txt -r dev-requirements.txt
          pyinstaller --onefile --name anime_rpc --optimize 2 --additional-hooks-dir=. launcher.py
      - name: Get version
        id: get_version
        shell: bash
        run: echo "version=$(python -c 'import anime_rpc; print(anime_rpc.__version__)')" >> $GITHUB_OUTPUT
      - name: Zip the module
        run: |
          cp LICENSE ./dist/LICENSE
          cp LICENSE ./extension/LICENSE
          Compress-Archive -Path dist/* -Destination anime_rpc_win.zip
          Compress-Archive -Path extension/* -Destination extension.zip
      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          artifacts: "./anime_rpc_win.zip"
