name: Build artifacts

on:
  push:
    branches: [ main ]

jobs:
    build:
        runs-on: [ubuntu-latest, windows-latest]

        steps:
          - name: Create Executable
            uses: sayyid5416/pyinstaller@v1
            with:
              python_ver: '3.10'
              spec: 'anime_rpc/__main__.py'
              requirements: 'requirements.txt'
              upload_exe_with_name: 'anime_rpc'
              options: --onefile